export const routes = {
  landing: "/",
  home: "/home",
  login: "/login",
  signup: "/signup",
  checkout: "/checkout",
  productDetails: "/product/:id",
  ads: "/ads",
  pendingproductdetails: "/pendingproduct/:id",
  logout: "/logout",
  users: "/users",
  userdetails: "/userdetails/:id",
  profile: "/profile",
  orders: "/orders",
  revenue:"/revenue",
};
